name: build

env:
  QT_VERSION: 5.15.2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: macos-11
    runs-on: macos-11
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          setup-python: false

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build

      - name: Build
        run: make -C ${{ github.workspace }}/build
