name: build

env:
  QT_VERSION: 6.2.4
  VTK_VERSION: 9.1.0
  CACHE_NUM: 0

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            arch: gcc_64
          - os: macos-11
            arch: macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Cache environment
        id: cache-env
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-qt-cache-${{ env.CACHE_NUM }}

      - name: Install Qt
        if: steps.cache-env.outputs.cache-hit != 'true'
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ env.QT_VERSION }}
          target: 'desktop'
          dir: '${{ github.workspace }}'
          install-deps: 'true'

      - name: Build VTK
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          cd ${{ github.workspace }}
          wget -q https://www.vtk.org/files/release/9.1/VTK-${VTK_VERSION}.tar.gz
          tar -xzf VTK-${VTK_VERSION}.tar.gz
          cd VTK-${VTK_VERSION}
          echo "::group::configure"
          mkdir build && cd build
          cmake \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${QT_VERSION}/${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_SHARED_LIBS=ON \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/Qt/${QT_VERSION}/${{ matrix.arch }} \
            -DVTK_GROUP_ENABLE_Qt=WANT \
            ..
          echo "::endgroup::"
          echo "::group::make"
          make -j2 install
          echo "::endgroup::"

      - name: Install dependencies (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt install libgl1-mesa-dev

      - name: Configure
        run: |
          cmake \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/Qt/${QT_VERSION}/${{ matrix.arch }} \
            -S . -B ${{ github.workspace }}/build

      - name: Build
        run: make -C ${{ github.workspace }}/build
