name: build

env:
  QT_VERSION: 6.3.2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-11', 'ubuntu-22.04' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies (linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update -qq
          sudo apt install qt6-base-dev libvtk9-qt-dev
          echo "QT6DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt6" >> $GITHUB_ENV

      - name: Install dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install vtk qt6
          echo "QT6DIR=$(brew --cellar)/qt@6/${{ env.QT_VERSION }}/lib/cmake/Qt6" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DQt6_DIR=${{ env.QT6DIR }}

      - name: Build
        run: make -C ${{ github.workspace }}/build
