name: release

env:
  QT_VERSION: 5.15.7_1

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  discussions: write

jobs:
  build-macos:
    name: release (macos)
    runs-on: macos-11
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install dependencies (macOS)
        run: |
          brew install vtk qt5
          echo "QT5DIR=$(brew --cellar)/qt@5/${{ env.QT_VERSION }}/lib/cmake/Qt5" >> $GITHUB_ENV
          echo "$(brew --cellar)/qt@5/${{ env.QT_VERSION }}/bin" >> $GITHUB_PATH

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DQt5_DIR=${{ env.QT5DIR }}

      - name: Build
        run: make -C ${{ github.workspace }}/build

      - name: Deploy app bundle
        run: |
          macdeployqt ${{ github.workspace }}/build/src/mesh-inspector.app
          cd ${{ github.workspace }}/build/src
          mv mesh-inspector.app "Mesh Inspector.app"
          zip -r mesh-inspector-${{ github.ref_name }}-macos-x86_64.zip "Mesh Inspector.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-x86_64
          path: "${{ github.workspace }}/build/src/mesh-inspector-${{ github.ref_name }}-macos-x86_64.zip"

  create-release:
    needs: [build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          discussion_category_name: announcements
          files: |
            macos-x86_64/mesh-inspector-${{ github.ref_name }}-macos-x86_64.zip
