name: release

env:
  QT_VERSION: 5.15.5_1

on: [workflow_dispatch]

jobs:
  build-macos:
    name: release (macOS X)
    runs-on: macos-11
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install dependencies (macOS)
        run: |
          brew install vtk qt5
          echo "QT5DIR=$(brew --cellar)/qt@5/${{ env.QT_VERSION }}/lib/cmake/Qt5" >> $GITHUB_ENV

      - name: Configure
        run: |
          cmake -S . -B ${{ github.workspace }}/build \
            -DQt5_DIR=${{ env.QT5DIR }}

      - name: Build
        run: make -C ${{ github.workspace }}/build

      - name: Deploy app bundle
        run: |
          macdeployqt ${{ github.workspace }}/build/src/mesh-inspector.app
          mv ${{ github.workspace }}/build/src/mesh-inspector.app "${{ github.workspace }}/build/src/Mesh Inspector.app"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mesh-inspector-v0.9-macosx-x86_64
          path: "${{ github.workspace }}/build/src/Mesh Inspector.app"

  create-release:
    needs: [build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
